### ISSUE TITLE
 The value of property hadoop.security.credential.provider.path must not be null

### ISSUE THREAD

**Issue by parisni** [yaooqinn/spark-ranger#3]
hi @yaooqinn ,

setup:

spark 2.4.4
ranger 0.7.0.2.6.5.0-292 (hdp build)
spark-ranger built with mvn clean package -Pspark-2.4 -Pranger-1.0 -DskipTests
service-name: used the one created and working for hive

I have the bellow error:

I am wondering if I should create a new hive service-name  (instead of reusing the one used by hive-server2). 

Thanks for your help.

```
ERROR RangerCredentialProvider: Unable to get the Credential Provider from the Configuration
java.lang.IllegalArgumentException: The value of property hadoop.security.credential.provider.path must not be null
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:92)
	at org.apache.hadoop.conf.Configuration.set(Configuration.java:1134)
	at org.apache.hadoop.conf.Configuration.set(Configuration.java:1115)
	at org.apache.ranger.authorization.hadoop.utils.RangerCredentialProvider.getCredentialProviders(RangerCredentialProvider.java:68)
	at org.apache.ranger.authorization.hadoop.utils.RangerCredentialProvider.getCredentialString(RangerCredentialProvider.java:46)
	at org.apache.ranger.plugin.util.RangerRESTClient.getCredential(RangerRESTClient.java:382)
	at org.apache.ranger.plugin.util.RangerRESTClient.getKeyManagers(RangerRESTClient.java:268)
	at org.apache.ranger.plugin.util.RangerRESTClient.buildClient(RangerRESTClient.java:188)
	at org.apache.ranger.plugin.util.RangerRESTClient.getClient(RangerRESTClient.java:176)
	at org.apache.ranger.plugin.util.RangerRESTClient.getResource(RangerRESTClient.java:156)
	at org.apache.ranger.admin.client.RangerAdminRESTClient.createWebResource(RangerAdminRESTClient.java:275)
	at org.apache.ranger.admin.client.RangerAdminRESTClient.access$300(RangerAdminRESTClient.java:48)
	at org.apache.ranger.admin.client.RangerAdminRESTClient$3.run(RangerAdminRESTClient.java:113)
	at org.apache.ranger.admin.client.RangerAdminRESTClient$3.run(RangerAdminRESTClient.java:111)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:360)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1678)
	at org.apache.ranger.admin.client.RangerAdminRESTClient.getServicePoliciesIfUpdated(RangerAdminRESTClient.java:121)
	at org.apache.ranger.plugin.util.PolicyRefresher.loadPolicyfromPolicyAdmin(PolicyRefresher.java:264)
	at org.apache.ranger.plugin.util.PolicyRefresher.loadPolicy(PolicyRefresher.java:202)
	at org.apache.ranger.plugin.util.PolicyRefresher.run(PolicyRefresher.java:171)
RROR PolicyRefresher: PolicyRefresher(serviceName=EDS_hive): failed to refresh policies. Will continue to use last known version of policies (1100)
java.lang.IllegalArgumentException: TrustManager is not specified
	at org.apache.commons.lang.Validate.notNull(Validate.java:192)
	at org.apache.ranger.plugin.util.RangerRESTClient.getSSLContext(RangerRESTClient.java:365)
	at org.apache.ranger.plugin.util.RangerRESTClient.buildClient(RangerRESTClient.java:190)
	at org.apache.ranger.plugin.util.RangerRESTClient.getClient(RangerRESTClient.java:176)
	at org.apache.ranger.plugin.util.RangerRESTClient.getResource(RangerRESTClient.java:156)
	at org.apache.ranger.admin.client.RangerAdminRESTClient.createWebResource(RangerAdminRESTClient.java:275)
	at org.apache.ranger.admin.client.RangerAdminRESTClient.access$300(RangerAdminRESTClient.java:48)
	at org.apache.ranger.admin.client.RangerAdminRESTClient$3.run(RangerAdminRESTClient.java:113)
	at org.apache.ranger.admin.client.RangerAdminRESTClient$3.run(RangerAdminRESTClient.java:111)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:360)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1678)
	at org.apache.ranger.admin.client.RangerAdminRESTClient.getServicePoliciesIfUpdated(RangerAdminRESTClient.java:121)
	at org.apache.ranger.plugin.util.PolicyRefresher.loadPolicyfromPolicyAdmin(PolicyRefresher.java:264)
	at org.apache.ranger.plugin.util.PolicyRefresher.loadPolicy(PolicyRefresher.java:202)
	at org.apache.ranger.plugin.util.PolicyRefresher.run(PolicyRefresher.java:171)

```

**Comment by yaooqinn** [comment]
Can you try ranger version in README
